"""Serve images generated by the ``CreateImage`` tool.

The ``CreateImage`` tool stores generated PNG files in the system temp
directory. The web frontend renders those images on a content card by pointing
an ``<img>`` tag at ``/api/images/<filename>``.

For safety this endpoint only serves ``.png`` files that live *directly* in the
system temp directory (never recursively), and it resolves symlinks to make sure
the served file cannot escape that directory.
"""

import logging
import os
import tempfile

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)

router = APIRouter()

# Directory where the CreateImage tool writes its temporary PNG files.
_IMAGE_DIR = os.path.realpath(tempfile.gettempdir())


@router.get("/{filename}")
async def get_image(filename: str):
    """Serve a generated image file by its base name."""
    # Reject path separators / traversal components outright.
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    if not filename.lower().endswith(".png"):
        raise HTTPException(status_code=400, detail="Only .png files are served")

    path = os.path.join(_IMAGE_DIR, filename)
    # Guard against symlink escapes: the resolved path must stay inside the
    # temp directory.
    real = os.path.realpath(path)
    if os.path.commonpath([real, _IMAGE_DIR]) != _IMAGE_DIR:
        raise HTTPException(status_code=400, detail="Invalid filename")

    if not os.path.isfile(real):
        raise HTTPException(status_code=404, detail="Image not found")

    return FileResponse(real, media_type="image/png")
