repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest stable version or pin as needed
    hooks:
      - id: ruff
        args: ["--fix"]  # Optional: auto-fix issues where possible

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version or pin as needed
    hooks:
      - id: black
