site_name: Janito Documentation
site_url: https://joaompinto.github.io/janito/
docs_dir: docs
repo_url: https://github.com/joaompinto/janito
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: guides/installation.md
  - Using Janito:
      - Quickstart & Basic Usage: guides/using.md
      - How Janito Uses Tools: guides/using_tools.md
      - Terminal Shell: guides/terminal_shell.md
      - One-Shot Terminal: guides/one_shot_terminal.md
      - Prompt Profiles & Styles: guides/prompt_profiles.md
      - Prompt Design Style: guides/prompting/prompt_design_style.md
  - Developing & Extending:
      - Developer Guide: guides/developing.md
      - Tools Developer Guide: guides/tools_developer_guide.md
      - Developer Toolchain Guide: meta/developer_toolchain.md
  - Code Intelligence:
      - Our Approach: code_intelligence/our_approach.md
      - Code Generation Challenges: code_intelligence/code_generation_challenges.md
      - Code Generation Observability: code_intelligence/code_generation_observability.md
      - Agentic Frameworks Comparison: code_intelligence/agentic_frameworks_comparison.md
  - Tools:
      - Overview: tools/index.md
      - Tools Reference:
          - Reference Table: tools/tools-reference.md
          - Ask User: tools/ask_user.md
          - Create Directory: tools/create_directory.md
          - Create File: tools/create_file.md
          - Fetch URL: tools/fetch_url.md
          - Find Files: tools/find_files.md
          - Get File Outline: tools/get_file_outline.md
          - Get Lines: tools/get_lines.md
          - Move File: tools/move_file.md
          - Present Choices: tools/present_choices.md
          - Remove Directory: tools/remove_directory.md
          - Remove File: tools/remove_file.md
          - Replace Text In File: tools/replace_text_in_file.md
          - Retrieve Memory: tools/retrieve_memory.md
          - Run Bash Command: tools/run_bash_command.md
          - Run PowerShell Command: tools/run_powershell_command.md
          - Run Python Command: tools/run_python_command.md
          - Search Files: tools/search_files.md
          - Search Text: tools/search_text.md
          - Store Memory: tools/store_memory.md
          - Validate File Syntax: tools/validate_file_syntax.md
  - Reference:
      - Architecture: reference/architecture.md
      - Configuration: reference/configuration.md
      - CLI Options: reference/cli-options.md
      - Azure OpenAI: reference/azure-openai.md
      - Message Handler Model:
          - Overview: reference/message-handler-model.md
          - Rich Message Handler: reference/rich-message-handler.md
      - API Reference: reference/api.md
  - Supported Models: supported-models.md
  - About:
      - Why Janito?: about/why.md
      - Janito vs Web Chat Agents: about/vs_webchats.md
      - Costs & Value Transparency: about/costs.md
  - Alternatives: ALTERNATIVES.md
# theme: readthedocs
# For more themes, see https://squidfunk.github.io/mkdocs-material/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc
  - tables
  - admonition
  - codehilite

extra:
  copyright: |
    Made with Material for MkDocs • Generated by <a href="https://janito.dev" target="_blank">janito.dev</a>
