site_name: Janito Documentation
site_url: https://joaompinto.github.io/janito/
docs_dir: docs
repo_url: https://github.com/joaompinto/janito
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: guides/installation.md
  - Using Janito:
      - Quickstart & Basic Usage: guides/using.md
      - How Janito Uses Tools: guides/using_tools.md
      - Terminal Shell: guides/terminal_shell.md
      - Costs & Value Transparency: guides/costs.md
  - Developing & Extending:
      - Developer Guide: guides/developing.md
      - Tools Developer Guide: guides/tools_developer_guide.md
      - Developer Toolchain Guide: meta/developer_toolchain.md
  - Reference:
      - Supported Models: supported-models.md
      - Architecture: reference/architecture.md
      - Configuration: reference/configuration.md
      - CLI Options: reference/cli-options.md
      - Azure OpenAI: reference/azure-openai.md
      - Message Handler Model:
          - Overview: reference/message-handler-model.md
          - Rich Message Handler: reference/rich-message-handler.md
      - Tools Reference: reference/tools-reference.md
  - About:
      - Why Janito?: guides/why.md
      - Janito vs Web Chat Agents: guides/vs_webchats.md
  - Alternatives: alternatives.md
# theme: readthedocs
# For more themes, see https://squidfunk.github.io/mkdocs-material/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc
  - tables
  - admonition
  - codehilite

extra:
  copyright: |
    Made with Material for MkDocs • Generated by <a href="https://janito.dev" target="_blank">janito.dev</a>
