// Pure formatting / rendering helpers for the chat component.
// No `this` dependencies beyond other component helpers — folded into the
// Alpine component via Object.assign in chat.js.

window.ChatFormatMixin = {
    formatTokens(n) {
        if (n === null || n === undefined) return '';
        if (n >= 1000000) return (n / 1000000).toFixed(1).replace(/\.0$/, '') + 'm';
        if (n >= 1000) return (n / 1000).toFixed(1).replace(/\.0$/, '') + 'k';
        return String(n);
    },

    // Format a tool execution duration (in milliseconds) for display.
    // Values below 1000ms are shown as milliseconds; 1000ms and above are
    // converted to seconds (e.g. 1000 -> "1s", 1500 -> "1.5s").
    formatDuration(ms) {
        if (ms === null || ms === undefined) return '';
        if (ms < 1000) return ms + 'ms';
        const seconds = ms / 1000;
        const rounded = Math.round(seconds * 10) / 10;
        return (Number.isInteger(rounded) ? rounded : rounded.toFixed(1)) + 's';
    },

    permLabel(perms) {
        if (!perms) return '';
        if (perms.includes('x')) return 'exec';
        if (perms.includes('w')) return 'write';
        if (perms.includes('r')) return 'read';
        return '';
    },

    permClass(perms) {
        const label = this.permLabel(perms);
        return label || 'read';
    },

    levelIcon(level) {
        const icons = {
            start: '', progress: '\u00b7', output: '', result: '\u2705',
            error: '\u274c', warning: '\u26a0\ufe0f', info: '\u2139\ufe0f',
        };
        return level in icons ? icons[level] : '\u00b7';
    },

    statusLabel(status) {
        return { running: 'Running', done: 'Done', error: 'Error' }[status] || status;
    },

    toolArgsStr(args) {
        try { return JSON.stringify(args, null, 2); }
        catch (e) { return String(args); }
    },

    toolResultStr(result) {
        if (result === null || result === undefined) return '';
        if (typeof result === 'string') return result;
        try { return JSON.stringify(result, null, 2); }
        catch (e) { return String(result); }
    },

    renderMarkdown(text) {
        return window.JanitoMarkdown ? window.JanitoMarkdown.render(text || '') : (text || '');
    },

    // Build the URL used to display an image generated by the CreateImage
    // tool. The backend serves generated temp files under /api/images/<name>.
    // When a bearer token is configured it is passed as a query param so the
    // <img> request is authorised by the TokenAuthMiddleware.
    imageUrl(path) {
        if (!path) return '';
        const name = String(path).split(/[\\/]/).pop();
        let url = '/api/images/' + encodeURIComponent(name);
        const token = window.__JANITO_TOKEN__;
        if (token) url += '?token=' + encodeURIComponent(token);
        return url;
    },

    // Sanitise SVG markup for safe inline rendering.  Uses DOMPurify
    // with the SVG profile when available; falls back to a regex-based
    // strip of <script> and event-handler attributes.
    sanitizeSvg(svgText) {
        if (!svgText) return '';
        if (typeof DOMPurify !== 'undefined') {
            return DOMPurify.sanitize(svgText, {
                USE_PROFILES: { svg: true, svgFilters: true },
            });
        }
        // Fallback: remove <script> tags and on* event attributes
        return svgText
            .replace(/<script[\s\S]*?<\/script>/gi, '')
            .replace(/\son\w+\s*=\s*"[^"]*"/gi, '')
            .replace(/\son\w+\s*=\s*'[^']*'/gi, '');
    },
};
